apiVersion: v1
data:
  {{- include "bd.defaultNonConfigurableEnvirons" . | nindent 2 }}
  {{- include "bd.postgresConnectionAdmin" . | nindent 2 }}
  {{- include "bd.postgresConnectionUser" . | nindent 2 }}
  {{- include "bd.environs" . | nindent 2 }}
  {{- include "enableSourceCodeUpload" . | nindent 2 }}
  {{- include "enableBinaryScanner" . | nindent 2 }}
  {{- include "enableIPV6" . | nindent 2 }}
  {{- include "enableAlert" . | nindent 2 }}
  {{- include "customNodePort" . | nindent 2 }}
kind: ConfigMap
metadata:
  labels:
    {{- include "bd.labels" . | nindent 4 }}
    component: configmap
  name: {{ .Release.Name }}-blackduck-config
  namespace: {{ .Release.Namespace }}
